server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment
  datasource:
    druid:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mycloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.suitspoon.provider.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

