server:
  port: 8006
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka01.com:7001/eureka/
feign:
  httpclient:
    connection-timeout: 5000
logging:
  level:
    com.suitspoon.providerfeign.web.ProviderFeignController: debug
    com.suitspoon.providerfeign.feign.ProviderFeign: debug
