server:
  port: 8002

spring:
  application:
    name: consumer-service


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka01.com:7001/eureka/,http://eureka02.com:7002/eureka/,http://eureka03.com:7003/eureka/
  instance:
    instance-id: su-consumer
    # eureka 客户端向服务端发送的心跳间隔时间
    lease-renewal-interval-in-seconds: 5
    # eureka 服务端收到最后一次心跳后的等待时间上限，超过就剔除服务
    lease-expiration-duration-in-seconds: 10